### ISSUE TITLE
"content.title" option is ignored

### ISSUE THREAD

**Issue by quatrano** [cytoscape/cytoscape.js-qtip#10]
The `content.title` option is ignored during qtip initialization.  eg:

```
elem.qtip({
  content: {
    title: 'My Title'
  }
});
```
or
```
elem.qtip({
  content: {
    title: function (event, api) {
      api.set('content.title', 'My Title');
    }
  }
});
```

In [this block](https://github.com/cytoscape/cytoscape.js-qtip/blob/2.2.5/cytoscape-qtip.js#L187) it looks like `content.title` is neglected, but it should receive the same treatment as `content.text`.  An easy workaround is to call `api.set('content.title', 'My Title');` from within my `content.text` function.

**Comment by maxkfranz** [comment]
Thanks, I've merged your PR
