### ISSUE TITLE
Show all qtips via clicking on a button.

### ISSUE THREAD

**Issue by bobg2013** [cytoscape/cytoscape.js-qtip#13]
Hi as per

http://stackoverflow.com/questions/35379725/how-to-show-all-qtips-in-cytoscape-js-on-button-click

Is it possible to show all qtips manually when a button is pressed? I have multiple qtips for certain types of nodes and I want to be able to toggle between having them show or not. When I try the code above I get an error. See the link.

Many thanks for all of your great work on this.

**Comment by maxkfranz** [comment]
Answered on SO; closing
