### ISSUE TITLE
removing a qtip bug

### ISSUE THREAD

**Issue by Kkevsterrr** [cytoscape/cytoscape.js-qtip#15]
Having an issue removing a qtip from cytsoscape nodes. Because the DOM elements are added on demand, qtip crashes when you try to run ```cy.elements('node').qtip("destroy");``` - it says, ```cannot read property set of undefined```. Qtip doesn't let you "overwrite" the qtip - it just renders two qtips on top of each other.  Similarly, using the api method, 
```cy.elements('node').qtip('api').destroy();```, although it doesn't cause an error, fails to actually remove the qtips. 
Updating qtips according to their documentation ```cy.elements('node').qtip('option', 'content', 'newcontent');``` gives a similar error.

**Comment by maxkfranz** [comment]
Thanks for the information.  This looks like a bug, so it will be looked into soon.

**Comment by maxkfranz** [comment]
After looking at this:

(1) `ele.qtip("destroy")` is not documented anywhere.  I don't know how you decided to call that, as it doesn't exist as an option.

(2) `cy.elements('node').qtip('api').destroy();` This works just fine on the demo page.

**Comment by Kkevsterrr** [comment]
I believe this works on the demo page because the qtips are always shown. When you set the qtips to only show on mouse hover, destroying the qtips was working for the ones I had hovered over, but did not work for the ones I had not yet hovered over.

**Comment by maxkfranz** [comment]
@Kkevsterrr 

Are you doing

(A) `ele.qtip({ show: { event: 'mouseover' } })`

or

(B) `ele.on('mouseover', function(){ ele.qtip(...) })`

?

As far as I know, (A) is the proper way to do things according to the qtip docs -- and the `api` object should be non-null after that call.  

If you use (B), you can't really avoid having to do a null check when you access the qtip `api` object.

**Comment by maxkfranz** [comment]
If you're using (B) because you want to use delegate selectors for elements not yet added to the graph, you can translate that to (A):

```js
cy.on('mouseover',  'node', function(){
  this.qtip(...); // options that show qtip now
});
```

becomes


```js
cy.on('add',  'node', function(){
  this.qtip({ show: { event: 'mouseover' }, ... }); // options that show qtip later on mouseover
});
```

That way, you guarantee the `api` object is always available for an element.

**Comment by Kkevsterrr** [comment]
My goal is to be able to dynamically update the tooltips of the graph.  My current code for displaying the tooltips is this: 

```javascript
cy.elements('node').qtip({
    content: function() {return get_qtip(this.data("id"), this.data("ip"), data)},
    position: {
        my: 'top center',
        at: 'bottom center'
    },
    show: { event: 'mouseover'  },
    hide: { event: 'mouseout' },
    style: {
            classes: 'qtip-bootstrap',
            tip: {
                width: 16,
                height: 8
             }
     }
});
```

I could never get qtip updating to work, so my solution was going to be remove all of the qtips and re-add them at each update. Both updating them and removing them though seem to fail for the same reason. Hopefully this helps clarify, and thank you so much for your help!

**Comment by Kkevsterrr** [comment]
@maxkfranz Any progress on this? The solutions you suggested unfortunately did not remedy my problem, and any help would be appreciated!

**Comment by maintrim** [comment]
cy.$('#id').qtip({  
   content: function() { 
      var btn = '<button class="btn btn-xs btn-default delCalendarEvent" onclick="this.style.visibility = \'hidden\';this.parentNode.parentNode.style.visibility = \'hidden\'" id="55">X</button>';
      return btn;
	 },
	  position: {
		my: 'top center',
		at: 'bottom center'
	  },
	  style: {
		classes: 'qtip-bootstrap',
		tip: {
		  width: 16,
		  height: 8
		}
	  }
	});
