### ISSUE TITLE
qTip is rendered for all parent elements when a child node is clicked.

### ISSUE THREAD

**Issue by istemi-bahceci** [cytoscape/cytoscape.js-qtip#16]
Hi, 

  When a child node is clicked which is inside a compound node, qTip pops up for the parents of this clicked node too. You can try qtip demo  of cytoscape-js with the following javascript code to reproduce the issue.

![image](https://cloud.githubusercontent.com/assets/8645080/15821950/a397a0c4-2bfb-11e6-9eb8-15ba80fc6adf.png)

Thanks,

```
$(function(){ // on dom ready

var cy = cytoscape({
  
  container: document.getElementById('cy'),
  
  boxSelectionEnabled: false,
  autounselectify: true,
  
  elements: {
    nodes: [
      { data: { id: 'n', parent: 'k', label: 'Tap me' } },
      { data: { id: 'k', label: 'Tap me' } }

    ]
  },
  
  layout: {
    name: 'grid',
    padding: 100
  },
  
  ready: function(){
    window.cy = this;
  },
  
  style: 'node { content: data(label); }'
});

// you can use qtip's regular options
// see http://qtip2.com/
cy.nodes().qtip({
  content: 'Hello!',
  position: {
    my: 'top center',
    at: 'bottom center'
  },
  style: {
    classes: 'qtip-bootstrap',
    tip: {
      width: 16,
      height: 8
    }
  }
});
  
}); // on dom ready
```

**Comment by maxkfranz** [comment]
Events bubble up to compound parents, just as events bubble on div parents in the DOM.  You'll have to use a custom event for compounds, e.g.

```js
nodes.qtip({ show: { event: 'directtap' } });

nodes.on('tap', function( e ){
  var eventIsDirect = e.cyTarget === this;
  
  if( eventIsDirect ){
    this.trigger('directtap');
  }
});
```

**Comment by istemi-bahceci** [comment]
@maxkfranz Thanks :) :+1:

**Comment by kavinnagul** [comment]
Hi Max,

I am using below code. But tooltip is not displaying?

cy.nodes().qtip({					 
			content: function(){ return 'Example qTip on ele ' + this.id() },
			position: {
				my: 'top center',
				at: 'bottom center'
			},
			style: {
				classes: 'qtip-bootstrap',
				tip: {
					width: 16,
					height: 8
				}
			},	
			show: { event: 'directtap' }
		}).on('tap', function( e ){		 
		  var eventIsDirect = e.cyTarget === this;

		  if( eventIsDirect ){
			this.trigger('directtap');
		  }
	});
eventIsDirect -> Its not returning true...

Can you Please help me?
