### ISSUE TITLE
qtip does not honor position

### ISSUE THREAD

**Issue by dacb** [cytoscape/cytoscape.js-qtip#2]
Great stuff, thank you.

I notice in the preview image that the qtips can be placed at various locations on the cytoscape elements, e.g. bottom center: ![Preview](https://raw.githubusercontent.com/cytoscape/cytoscape.js-qtip/b581bf094a7d1dfa04a174326bc22db4a5a9dc14/img/preview.png)

However, when I clone the repo (git rev-parse HEAD = 72be0c802e8c92126f054e06fcec2e4a55d7e9ac) and render demo.html in Safari and Firefox, the tips appear only in the center of a node. 
![cytojs](https://cloud.githubusercontent.com/assets/6485498/4985562/b519dfba-692e-11e4-84d3-25c1c96a5c43.png)

Looking at the demo.html source, it seems to intend that they display at the bottom center as in the preview image above: ![these lines](https://github.com/cytoscape/cytoscape.js-qtip/blob/b581bf094a7d1dfa04a174326bc22db4a5a9dc14/demo.html/#L40-41)

Any thoughts?

**Comment by NoahStahl** [comment]
Nice work Max. I'm not sure if this is the same issue being discussed, but I found that the position.adjust.x/y option values were not being respected by the extension code. It seems that the passed in option values are ignored when recalculating the adjustment. I added some code which seems to resolve this in both instances of the updatePosition function:
```
var optsXOffset = passedOpts.position.adjust.x || 0;
var optsYOffset = passedOpts.position.adjust.y || 0;

qtipApi.set('position.adjust.x', cOff.left + pos.x + window.pageXOffset + optsXOffset);
qtipApi.set('position.adjust.y', cOff.top + pos.y + window.pageYOffset + optsYOffset);
```

WIth this in place, the following works well:
```
// Set a qTip tooltip to display full name on mouseover
        graphObject.elements().forEach(function (element) {
            var nodeName = element.data("name");
            if (nodeName) {
                element.qtip({
                    content: {
                        text: nodeName
                    },
                    position: {
                        my: 'bottom center',
                        at: 'bottom center',
                        adjust: {
                            y: 50,
                            mouse: false
                        }
                    },
                    show: {
                        event: 'mouseover'
                    },
                    hide: {
                        event: 'click mouseout'
                    },
                    style: {
                        classes: 'qtip-tipsy'
                    }
                });
            }
        });
```

**Comment by maxkfranz** [comment]
Yes, the position adjust values are needed for the base positioning of the qtips in the graph canvas.  It's somewhat related, but would mean that additional logic may be needed in order to maintain both the internal adjust and the dev-specified adjust.

**Comment by maxkfranz** [comment]
@NoahStahl, @dacb 

I think this change should do it for both your usecases.  I tested it a bit, but please let me know if it works well for you.

**Comment by NoahStahl** [comment]
Excellent, thanks Max. The updated version is working well in my setup.
