### ISSUE TITLE
Show qtip on hover or right click

### ISSUE THREAD

**Issue by djangosdk** [cytoscape/cytoscape.js-qtip#24]
Is it possible to have qtip be shown on 

1. As context menu , means by right clicking element
2. Show on hover(mouse-over) instead of left click (so that I can do another action on left click). should be configurable to hide qtip on mouse-out or not so that user can interact with html in qtip

These 2 will be very helpful additions to qTip

**Comment by maxkfranz** [comment]
As the readme says, just use the qtip `options` and API:

http://qtip2.com/options#show.event

e.g. mouseover, cxttap
