### ISSUE TITLE
Not show qtip on node on React Project

### ISSUE THREAD

**Issue by luli-isa** [cytoscape/cytoscape.js-qtip#26]
Hi,
I must show a popover when tne user mouseover on a node on my graph.
I add this line code 

`cy.nodes().qtip({
      content: 'hi',
      position: {
        my: 'top center',
        at: 'bottom center'
      }
    })`

but the popover is show at the end of the generic html div in which there is the graph drawed and not on single node

**Comment by maxkfranz** [comment]
See https://github.com/cytoscape/cytoscape.js-qtip/issues/27#issuecomment-298685167

You probably have `body { position: static; }`

**Comment by luli-isa** [comment]
I try change the body from static to absolute position but It doesn't work :-(

**Comment by maxkfranz** [comment]
Maybe you're missing the qtip stylesheet?

**Comment by gflowers2012** [comment]
Having an issue where the tooltip is showing outside of the container region for the cytoscape graph.
![qtip error](https://user-images.githubusercontent.com/16093861/28389746-4ba050dc-6c8c-11e7-8c31-61d9ac087173.PNG)

Code below:

`let cy1 = cytoscape({

      container: conf,
      elements: CytospaceGraphData.elements,
      layout: options,

      style: [
        {
          selector: 'node',
          style: {
            'content': 'data(label)'
          }
        },
        {
          selector: 'edge',
          style: {
            'mid-target-arrow-color': 'black',
            'mid-target-arrow-shape': 'triangle',
            'arrow-scale': '3'
          }
        }
      ]
    });

    cy1.on('click', 'node', function (e) {
      console.log(e);

      var x = e.position.x;
      var y = e.position.y;

      e.target.qtip({
        overwrite: false, // Make sure the tooltip won't be overridden once created
        content: 'Hello!',
        position: {
          my: 'top center',
          at: 'bottom center',
          target: [x + 3, y + 3],
          adjust: { x: 7, y: 7 }
        },
        hide: {
          event: 'click',
          fixed: true,
          event: false,
          inactive: 2000
        },
        style: {
          classes: 'qtip-bootstrap',
          width: 200,
          tip: {
            corner: true,
            width: 24,
            height: 24
          }
        }
      }, event); // Pass through our live event to qTip
    });`
