### ISSUE TITLE
Edge tooltip position not correct

### ISSUE THREAD

**Issue by preraksola** [cytoscape/cytoscape.js-qtip#27]
By using the library, the tooltip for nodes is working completely fine but for the edges, they are displayed at the top right corner of the screen. I am using the same code for both nodes and edges. Below is the code that I tried:
```
cy.edges().qtip({
    content: function () {
        return 'Expression: ' + this.data('value')
    },
    position: {
        my: 'top center',
        at: 'bottom center'
    },
    style: {
        classes: 'qtip-bootstrap',
	tip: {
		width: 16,
		height: 8
	}
    },
    show: {
	event: 'click',
	solo: true,
	effect: function (offset) {
		$(this).slideDown(100); // "this" refers to the tooltip
	}
    }
});
```

I also tried with `target: mouse` without using this library but the result were the same:
```
cy.on('tap', 'edge', function (evt) {
    evt.target.qtip({
        content: function () {
	    return 'Expression: ' + this.data('value')
        },
	position: {
	    target: 'mouse'
	},
	style: {
	    classes: 'qtip-bootstrap',
	    tip: {
	        width: 16,
		height: 8
	    }
	},
	show: {
	    event: 'click',
	    solo: true,
	    effect: function (offset) {
	        $(this).slideDown(100); // "this" refers to the tooltip
	    }
	}
    });
});
```

**Comment by maxkfranz** [comment]
I don't think qtip itself works well unless the root element (html or body) is non-static.  That's why the demo has 

```
body, html {
				font-family: helvetica;
				font-size: 14px;
				width: 100%;
				height: 100%;
				position: absolute;
				padding: 0;
				margin: 0;
			}
```

**Comment by preraksola** [comment]
If I make the parent div's `position: absolute`, my graph is not rendered at all. It renders only for `position: relative`

**Comment by preraksola** [comment]
Here's a fiddle with reproduced issue: https://jsfiddle.net/prerak6962/4anx7eqt/8/
The css is same as that mentioned in the example.

**Comment by maxkfranz** [comment]
Thanks for the example.  Try cytoscape-edgehandles@2.7.1

**Comment by nitin291989** [comment]
Hi Maxkfranz,

I am also facing the same issue where am getting the correct position of tooptip for Nodes but for edges it is showing the tooltip on top left corner of the screen.
While looking into the jQuery qtip library, jquery.qtip.js, i have found that for egdes the "target" option of "position" is an array of two elements [0,0] due to which tooltip appearing on the top left of the screen whereas for Nodes it's not an array hence correct position of tooptip.
This seems to be the possible reason of this problem.
Another observation is that, in cytoscape-qtip.js library, in updateposition function there is a variable used "isNode", which make this function and position setting for Nodes only and not for any other element.

Could you please suggest how this issue can be resolved.

Thanks

**Comment by maxkfranz** [comment]
Edge positioning seems to work fine.  Just follow the docs.  There's a working example in the demo.

**Comment by nitin291989** [comment]
Thanks Max  for your response!

It would be really great if you could please share the doc and example links.

Thanks.

**Comment by nitin291989** [comment]
Hello Max,

I have checked the Demo example at the following link:
    [https://github.com/cytoscape/cytoscape.js-qtip]

Using the cytoscape-qtip.js file from there, i can see the tooltip bubble box at correct position for edges.

But, i am getting the tooltip bubble box at [0,0] location i.e top left corner of screen as well. So there are 2 tooltip bubble box appearing at the same time, one at the correct mouse location on edge, other one at the [0,0] location i.e top left corner of screen.

when i comment out the following line in cytoscape-qtip.js, the problem of extra tooltip bubble box at [0,0] location is resolved:
         `opts.position.target = [0, 0];  // Line no. 201`

Please comment.

Thanks & Regards.

**Comment by arpitmrana** [comment]
Hello Max,

Nitin is right. 
cytoscape-qtip.js shows the same behavior as described above for the body having property position=relative. 
Even if I commented line no. 201- 
opts.position.target = [0, 0];
but for mouseover and show.ready = true, tooltip box positions at the lastly generated tooltip position. 

Please suggest some way out.

Thanks

**Comment by VinLau** [comment]
Hey Max,

I get a similar issue as above. Whenever I set the qTip on an edge to ready : true the qTip position is on the top-left not on the edge.

Cheers.

**Comment by wlchn** [comment]
Worked nicely when I update to 2.7.1
