### ISSUE TITLE
Is it possible to new line in qtip content text?

### ISSUE THREAD

**Issue by stardustrain** [cytoscape/cytoscape.js-qtip#29]
I'd like to including new line character such as '\n' in qtip content text.
e.g.) 
``` javascript
cy.on('click', 'edge', function(e){
  var test = 'test'
  this.qtip({
    content: {text: `test\n${test}`}
});
```

But not work '\n'. 
Is it had to finding other way instead of using '\n'?

**Comment by maxkfranz** [comment]
A newline doesn't do anything in HTML: http://stackoverflow.com/questions/5782409/why-doesnt-javascript-newlines-work-inside-html
