### ISSUE TITLE
Edge tooltip position is not working as expected

### ISSUE THREAD

**Issue by nitin291989** [cytoscape/cytoscape.js-qtip#30]
I am facing an issue where am getting the correct position of tooptip for Nodes but for edges it is showing the tooltip on top left corner of the screen.
While looking into the jQuery qtip library, jquery.qtip.js, i have found that for egdes the "target" option of "position" is an array of two elements [0,0] due to which tooltip appearing on the top left of the screen whereas for Nodes it's not an array hence correct position of tooptip.
This seems to be the possible reason of this problem.
Another observation is that, in cytoscape-qtip.js library, in updateposition function there is a variable used "isNode", which make this function and position setting for Nodes only and not for any other element.

I have checked the Demo example at the following link:
[https://github.com/cytoscape/cytoscape.js-qtip](https://github.com/cytoscape/cytoscape.js-qtip)

Using the cytoscape-qtip.js file from there, i can see the tooltip bubble box at correct position for edges.

But, i am getting the tooltip bubble box at [0,0] location i.e top left corner of screen as well. So there are 2 tooltip bubble box appearing at the same time, one at the correct mouse location on edge, other one at the [0,0] location i.e top left corner of screen.

when i comment out the following line in cytoscape-qtip.js, the problem of extra tooltip bubble box at [0,0] location is resolved:
`opts.position.target = [0, 0]; // Line no. 201`

Could any help, how to proceed on this.

Thanks & Regards.

**Comment by nitin291989** [comment]
I have found the solution for this issue.

Could anybody let me know how can i provide the solution authentically for this project! So that fix can be published for everybody.

Thanks & Regards.

**Comment by maxkfranz** [comment]
The demo works for edges.  We can look into issues only if you can provide a reproducible test case that fails.

If you can come up with a valid test case that fails, then post it here.  Otherwise, just follow the docs.

**Comment by nitin291989** [comment]
Here is the example which i am working upon:

It consist of compound nodes, where edges(if any) are there between child nodes only.

### **index.html**
[index.txt](https://github.com/cytoscape/cytoscape.js-qtip/files/1269650/index.txt)

### **code.js**
[code.txt](https://github.com/cytoscape/cytoscape.js-qtip/files/1269661/code.txt)

### Following zip file includes all the libraries which i have used:
[libraries.zip](https://github.com/cytoscape/cytoscape.js-qtip/files/1269672/libraries.zip)

### Snapshot of the diagram with multiple qtip bubble for edge:
![cytoscape_demo](https://user-images.githubusercontent.com/20776063/29962152-c0282e60-8f1f-11e7-9ec5-4649f0129775.png)

**Comment by nitin291989** [comment]
Hello Max,

Hope you were able to get my code attached in my previous comment and run it.
Please let me know if there any mistake in my code.

Thanks & Regards.
Nitin
