### ISSUE TITLE
Click on node label doesn't open qTip

### ISSUE THREAD

**Issue by ronkpunk** [cytoscape/cytoscape.js-qtip#31]
Hi & congrats for your plugins.
I'm using to display multiple information related to a node but I've a problem.

the code works fine when I click on the node.
If I click on the node label (content) qTip doesn't appear.

I try to add cy.emit to trigger node tap with no luck
I also try to change the selector of cy.$('#myid').qTip... in cy.$('#myid, #myid:after, #myid:before').qTip... (hoping that 'content' attribute was "that" kind of content but it doesn't work yet.

Is it possible to achieve this task?
How?

Thank you in advance
ronkpunk

**Comment by maxkfranz** [comment]
Closing, as cytoscape-popper has superseded this extension:

https://github.com/cytoscape/cytoscape.js-popper
