### ISSUE TITLE
Showing multiple qtips on different nodes is broken

### ISSUE THREAD

**Issue by destiny117** [cytoscape/cytoscape.js-qtip#32]
After updating to cytoscape 3 and the current cytoscape-qtip i can no longer show multiple qtips at different nodes, all are shown at the same node (the last one called)..
the problem was introduced with commit 7dbcff0995a9f3d65eb8d626943d87c6601a60fe
before that it was working correctly

**Comment by maxkfranz** [comment]
I've confirmed that it's working properly.  It can be tricky to use qtip, and you have to set all its options appropriately for how you want it to behave.  The default `hide.event: 'unfocus'`, for example, will hide the first qtip on clicking for a second one.

The demo works with this:

```js
				cy.elements().qtip({
					content: function(){ return 'Example qTip on ele ' + this.id() },
					position: {
						my: 'top center',
						at: 'bottom center'
					},
					hide: {
						event: 'donthide'
					},
					style: {
						classes: 'qtip-bootstrap',
						tip: {
							width: 16,
							height: 8
						}
					}
				});
```

<img width="464" alt="screen shot 2017-12-11 at 2 29 59 pm" src="https://user-images.githubusercontent.com/989043/33849886-00684924-de80-11e7-96ec-f554aac13736.png">
