### ISSUE TITLE
Allow jQuery 3.x (there is an XSS vulnerability in previous versions)

### ISSUE THREAD

**Issue by nicky1038** [cytoscape/cytoscape.js-qtip#33]
As for now *cytoscape.js-qtip* requires "`jQuery ^2.0 || ^1.10.0`, as *qTip* requires it".

But *qTip2* requires `"jquery": ">=1.6.0"`, i.e. it allows 3.x versions too.

It should be possible to use *jQuery* 3.x, and it seems `cytoscape.js-qtip` won't break form this change too.

Motivation: `npm audit` shows "Cross-Site Scripting (XSS)" vulnerability for *jQuery* 2.x.

I'd just specify `"jquery": ">=1.6.0"` in `peerDependencies` as in *qTip2*.

Opening this issue instead of a pull request to make sure if *jQuery* 3.x was not disallowed intentionally.

**Comment by maxkfranz** [comment]
When qtip was last supported by its author, jquery v2 was the latest version I think.  Qtip is no longer supported by its author at all, it seems, so it's difficult to say whether newer versions of jquery will work properly with cytoscape-qtip going forward.

I suppose we could update package.json, but in any case I'd recommend everyone to use cytoscape-popper instead --- where possible.  It doesn't require jquery.   Popper is an active project, and it's more flexible.

**Comment by nicky1038** [comment]
> When qtip was last supported by its author, jquery v2 was the latest version I think.

Got it. The release date for jQuery 3.0.0-rc1 (first 3.x) is May 20, 2016, and the last significant commit for qTip2 was on May 12, 2016, so it's clear the author didn't make sure if qTip2 works with jQuery 3.x.

There is a minor compatibility issue, and a pull request (yet unaccepted...) fixing it:
https://github.com/qTip2/qTip2/pull/818
This simple check could be done in `generateOpts` function in this package. (For every jQuery version I guess).

One more (minor) issue is a deprecation warning for internal `delegate` method call in brower console:
https://github.com/qTip2/qTip2/issues/824
Unfortunately, there's nothing to do here.

For the rest it should work :)
Waiting for reply from you - what do you think about the proposed change (a check for `$(window)`)? And then I'll do a pull request.

**Comment by maxkfranz** [comment]
I'm open to any workaround that doesn't break the extension for the versions of jquery that are officially supported by qtip.

**Comment by maxkfranz** [comment]
Oops, wrong button...
