### ISSUE TITLE
"position.target" can't be overridden

### ISSUE THREAD

**Issue by quatrano** [cytoscape/cytoscape.js-qtip#9]
The `position.target` option is ignored during qtip initialization, and is always set to `[0, 0]` [here](https://github.com/cytoscape/cytoscape.js-qtip/blob/2.2.5/cytoscape-qtip.js#L156). I was interested in using: 
```
elem.qtip({
  position: {
    target: 'mouse'
  }
});
```

I'm sure this is related to how you've adapted qtip to work with non-HTMLDomElements, so `position.target = 'mouse'` may not be feasible, but I thought it should be documented.

**Comment by maxkfranz** [comment]
I've added a note.  If you need to use `mouse`, you don't really need the extension.  You can call qTip directly on a div in that case.  If you want to trigger the qtip on a cy event, just `$div.trigger('customevent')` with `options.show.event: 'customevent'`

**Comment by quatrano** [comment]
good workaround, thanks!
